FROM neo4j

ADD https://github.com/neo4j-contrib/neo4j-graph-algorithms/releases/download/3.5.4.0/graph-algorithms-algo-3.5.4.0.jar /var/lib/neo4j/plugins/

ENV NEO4J_dbms_security_procedures_unrestricted=algo.\\\*
